package model.services;

import model.entities.PhoneNumber;
import model.exceptions.ThereIsNoAreaCodeException;
import model.exceptions.ThereIsNoDDIException;

public class AreaCode {
    private static String getUsOrCanadaRegionByAreaCode(PhoneNumber phoneNumber){
        return switch (phoneNumber.getAreaCode()) {
            case "201", "551" -> "United States\nRegion: Jersey City, NJ";
            case "202" -> "United States\nRegion: District of Columbia";
            case "203" -> "United States\nRegion: Bridgeport, CT";
            case "205" -> "United States\nRegion: Birmingham, AL";
            case "206" -> "United States\nRegion: Seattle, WA";
            case "207" -> "United States\nRegion: Portland, ME";
            case "208" -> "United States\nRegion: Idaho";
            case "209" -> "United States\nRegion: Stockton, CA";
            case "210" -> "United States\nRegion: San Antonio, TX";
            case "212" -> "United States\nRegion: New York, NY";
            case "213" -> "United States\nRegion: Los Angeles, CA";
            case "214" -> "United States\nRegion: Dallas, TX";
            case "215" -> "United States\nRegion: Philadelphia, PA";
            case "216" -> "United States\nRegion: Cleveland, OH";
            case "217" -> "United States\nRegion: Springfield, IL";
            case "218" -> "United States\nRegion: Duluth, MN";
            case "219" -> "United States\nRegion: Hammond, IN";
            case "220" -> "United States\nRegion: Newark, OH";
            case "223" -> "United States\nRegion: Lancaster, PA";
            case "224" -> "United States\nRegion: Elgin, IL";
            case "225" -> "United States\nRegion: Baton Rouge, LA";
            case "228" -> "United States\nRegion: Gulfport, MS";
            case "229" -> "United States\nRegion: Albany, GA";
            case "231" -> "United States\nRegion: Muskegon, MI";
            case "234" -> "United States\nRegion: Akron, OH";
            case "239" -> "United States\nRegion: Cape Coral, FL";
            case "240" -> "United States\nRegion: Germantown, MD";
            case "248" -> "United States\nRegion: Troy, MI";
            case "251" -> "United States\nRegion: Mobile, AL";
            case "252" -> "United States\nRegion: Greenville, NC";
            case "253" -> "United States\nRegion: Tacoma, WA";
            case "254" -> "United States\nRegion: Killeen, TX";
            case "256" -> "United States\nRegion: Huntsville, AL";
            case "260" -> "United States\nRegion: Fort Wayne, IN";
            case "262" -> "United States\nRegion: Kenosha, WI";
            case "267" -> "United States\nRegion: Philadelphia, PA";
            case "269" -> "United States\nRegion: Kalamazoo, MI";
            case "270" -> "United States\nRegion: Bowling Green, KY";
            case "272" -> "United States\nRegion: Scranton, PA";
            case "276" -> "United States\nRegion: Bristol, VA";
            case "279" -> "United States\nRegion: Sacramento, CA";
            case "281" -> "United States\nRegion: Houston, TX";
            case "301" -> "United States\nRegion: Germantown, MD";
            case "302" -> "United States\nRegion: Delaware";
            case "303" -> "United States\nRegion: Denver, CO";
            case "304" -> "United States\nRegion: West Virginia";
            case "305" -> "United States\nRegion: Miami, FL";
            case "307" -> "United States\nRegion: Wyoming";
            case "308" -> "United States\nRegion: Grand Island, NE";
            case "309" -> "United States\nRegion: Peoria, IL";
            case "310" -> "United States\nRegion: Los Angeles, CA";
            case "312" -> "United States\nRegion: Chicago, IL";
            case "313" -> "United States\nRegion: Detroit, MI";
            case "314" -> "United States\nRegion: St. Louis, MO";
            case "315" -> "United States\nRegion: Syracuse, NY";
            case "316" -> "United States\nRegion: Wichita, KS";
            case "317" -> "United States\nRegion: Indianapolis, IN";
            case "318" -> "United States\nRegion: Shreveport, LA";
            case "319" -> "United States\nRegion: Cedar Rapids, IA";
            case "320" -> "United States\nRegion: St. Cloud, MN";
            case "321" -> "United States\nRegion: Orlando, FL";
            case "323" -> "United States\nRegion: Los Angeles, CA";
            case "325" -> "United States\nRegion: Abilene, TX";
            case "326" -> "United States\nRegion: Dayton, OH";
            case "330" -> "United States\nRegion: Akron, OH";
            case "331" -> "United States\nRegion: Aurora, IL";
            case "332" -> "United States\nRegion: New York, NY";
            case "334" -> "United States\nRegion: Montgomery, AL";
            case "336" -> "United States\nRegion: Greensboro, NC";
            case "337" -> "United States\nRegion: Lafayette, LA";
            case "339" -> "United States\nRegion: Boston, MA";
            case "340" -> "United States\nRegion: Virgin Islands";
            case "341" -> "United States\nRegion: Oakland, CA";
            case "346" -> "United States\nRegion: Houston, TX";
            case "347" -> "United States\nRegion: New York, NY";
            case "350" -> "United States\nRegion: Stockton, CA";
            case "351" -> "United States\nRegion: Lowell, MA";
            case "352" -> "United States\nRegion: Gainesville, FL";
            case "360" -> "United States\nRegion: Vancouver, WA";
            case "361" -> "United States\nRegion: Corpus Christi, TX";
            case "363" -> "United States\nRegion: Hempstead, NY";
            case "364" -> "United States\nRegion: Bowling Green, KY";
            case "380" -> "United States\nRegion: Columbus, OH";
            case "385" -> "United States\nRegion: Salt Lake City, UT";
            case "386" -> "United States\nRegion: Palm Coast, FL";
            case "401" -> "United States\nRegion: Providence, RI";
            case "402" -> "United States\nRegion: Omaha, NE";
            case "404" -> "United States\nRegion: Atlanta, GA";
            case "405" -> "United States\nRegion: Oklahoma City, OK";
            case "406" -> "United States\nRegion: Montana";
            case "407" -> "United States\nRegion: Orlando, FL";
            case "408" -> "United States\nRegion: San Jose, CA";
            case "409" -> "United States\nRegion: Beaumont, TX";
            case "410" -> "United States\nRegion: Baltimore, MD";
            case "412" -> "United States\nRegion: Pittsburgh, PA";
            case "413" -> "United States\nRegion: Springfield, MA";
            case "414" -> "United States\nRegion: Milwaukee, WI";
            case "415" -> "United States\nRegion: San Francisco, CA";
            case "417" -> "United States\nRegion: Springfield, MO";
            case "419" -> "United States\nRegion: Toledo, OH";
            case "423" -> "United States\nRegion: Chattanooga, TN";
            case "424" -> "United States\nRegion: Los Angeles, CA";
            case "425" -> "United States\nRegion: Bellevue, WA";
            case "430" -> "United States\nRegion: Tyler, TX";
            case "432" -> "United States\nRegion: Midland, TX";
            case "434" -> "United States\nRegion: Lynchburg, VA";
            case "435" -> "United States\nRegion: St. George, UT";
            case "440" -> "United States\nRegion: Parma, OH";
            case "442" -> "United States\nRegion: Oceanside, CA";
            case "443" -> "United States\nRegion: Baltimore, MD";
            case "445" -> "United States\nRegion: Philadelphia, PA";
            case "447" -> "United States\nRegion: Springfield, IL";
            case "448" -> "United States\nRegion: Tallahassee, FL";
            case "458" -> "United States\nRegion: Eugene, OR";
            case "463" -> "United States\nRegion: Indianapolis, IN";
            case "464" -> "United States\nRegion: Cicero, IL";
            case "469" -> "United States\nRegion: Dallas, TX";
            case "470" -> "United States\nRegion: Atlanta, GA";
            case "472" -> "United States\nRegion: Fayetteville, NC";
            case "475" -> "United States\nRegion: Bridgeport, CT";
            case "478" -> "United States\nRegion: Macon, GA";
            case "479" -> "United States\nRegion: Fort Smith, AR";
            case "480" -> "United States\nRegion: Mesa, AZ";
            case "484" -> "United States\nRegion: Allentown, PA";
            case "501" -> "United States\nRegion: Little Rock, AR";
            case "502" -> "United States\nRegion: Louisville, KY";
            case "503" -> "United States\nRegion: Portland, OR";
            case "504" -> "United States\nRegion: New Orleans, LA";
            case "505" -> "United States\nRegion: Albuquerque, NM";
            case "507" -> "United States\nRegion: Rochester, MN";
            case "508" -> "United States\nRegion: Worcester, MA";
            case "509" -> "United States\nRegion: Spokane, WA";
            case "510" -> "United States\nRegion: Oakland, CA";
            case "512" -> "United States\nRegion: Austin, TX";
            case "513" -> "United States\nRegion: Cincinnati, OH";
            case "515" -> "United States\nRegion: Des Moines, IA";
            case "516" -> "United States\nRegion: Hempstead, NY";
            case "517" -> "United States\nRegion: Lansing, MI";
            case "518" -> "United States\nRegion: Albany, NY";
            case "520" -> "United States\nRegion: Tucson, AZ";
            case "530" -> "United States\nRegion: Redding, CA";
            case "531" -> "United States\nRegion: Omaha, NE";
            case "534" -> "United States\nRegion: Eau Claire, WI";
            case "539" -> "United States\nRegion: Tulsa, OK";
            case "540" -> "United States\nRegion: Roanoke, VA";
            case "541" -> "United States\nRegion: Eugene, OR";
            case "557" -> "United States\nRegion: St. Louis, MO";
            case "559" -> "United States\nRegion: Fresno, CA";
            case "561" -> "United States\nRegion: West Palm Beach, FL";
            case "562" -> "United States\nRegion: Long Beach, CA";
            case "563" -> "United States\nRegion: Davenport, IA";
            case "564" -> "United States\nRegion: Vancouver, WA";
            case "567" -> "United States\nRegion: Toledo, OH";
            case "570" -> "United States\nRegion: Scranton, PA";
            case "571" -> "United States\nRegion: Arlington, VA";
            case "572" -> "United States\nRegion: Oklahoma City, OK";
            case "573" -> "United States\nRegion: Columbia, MO";
            case "574" -> "United States\nRegion: South Bend, IN";
            case "575" -> "United States\nRegion: Las Cruces, NM";
            case "580" -> "United States\nRegion: Lawton, OK";
            case "582" -> "United States\nRegion: Erie, PA";
            case "585" -> "United States\nRegion: Rochester, NY";
            case "586" -> "United States\nRegion: Warren, MI";
            case "601" -> "United States\nRegion: Jackson, MS";
            case "602" -> "United States\nRegion: Phoenix, AZ";
            case "603" -> "United States\nRegion: New Hampshire";
            case "605" -> "United States\nRegion: South Dakota";
            case "606" -> "United States\nRegion: Ashland, KY";
            case "607" -> "United States\nRegion: Binghamton, NY";
            case "608" -> "United States\nRegion: Madison, WI";
            case "609" -> "United States\nRegion: Trenton, NJ";
            case "610" -> "United States\nRegion: Allentown, PA";
            case "612" -> "United States\nRegion: Minneapolis, MN";
            case "614" -> "United States\nRegion: Columbus, OH";
            case "615" -> "United States\nRegion: Nashville, TN";
            case "616" -> "United States\nRegion: Grand Rapids, MI";
            case "617" -> "United States\nRegion: Boston, MA";
            case "618" -> "United States\nRegion: Belleville, IL";
            case "619" -> "United States\nRegion: San Diego, CA";
            case "620" -> "United States\nRegion: Hutchinson, KS";
            case "623" -> "United States\nRegion: Phoenix, AZ";
            case "626" -> "United States\nRegion: Pasadena, CA";
            case "628" -> "United States\nRegion: San Francisco, CA";
            case "629" -> "United States\nRegion: Nashville, TN";
            case "630" -> "United States\nRegion: Aurora, IL";
            case "631" -> "United States\nRegion: Brentwood, NY";
            case "636" -> "United States\nRegion: O'Fallon, MO";
            case "640" -> "United States\nRegion: Trenton, NJ";
            case "641" -> "United States\nRegion: Mason City, IA";
            case "646" -> "United States\nRegion: New York, NY";
            case "650" -> "United States\nRegion: San Mateo, CA";
            case "651" -> "United States\nRegion: St. Paul, MN";
            case "656" -> "United States\nRegion: Tampa, FL";
            case "657" -> "United States\nRegion: Anaheim, CA";
            case "659" -> "United States\nRegion: Birmingham, AL";
            case "660" -> "United States\nRegion: Sedalia, MO";
            case "661" -> "United States\nRegion: Bakersfield, CA";
            case "662" -> "United States\nRegion: Southaven, MS";
            case "667" -> "United States\nRegion: Baltimore, MD";
            case "669" -> "United States\nRegion: San Jose, CA";
            case "670" -> "United States\nRegion: Northern Mariana Islands";
            case "671" -> "United States\nRegion: Guam";
            case "678" -> "United States\nRegion: Atlanta, GA";
            case "680" -> "United States\nRegion: Syracuse, NY";
            case "681" -> "United States\nRegion: West Virginia";
            case "682" -> "United States\nRegion: Fort Worth, TX";
            case "684" -> "United States\nRegion: American Samoa";
            case "689" -> "United States\nRegion: Orlando, FL";
            case "701" -> "United States\nRegion: North Dakota";
            case "702" -> "United States\nRegion: Las Vegas, NV";
            case "703" -> "United States\nRegion: Arlington, VA";
            case "704" -> "United States\nRegion: Charlotte, NC";
            case "706" -> "United States\nRegion: Augusta, GA";
            case "707" -> "United States\nRegion: Santa Rosa, CA";
            case "708" -> "United States\nRegion: Cicero, IL";
            case "712" -> "United States\nRegion: Sioux City, IA";
            case "713" -> "United States\nRegion: Houston, TX";
            case "714" -> "United States\nRegion: Anaheim, CA";
            case "715" -> "United States\nRegion: Eau Claire, WI";
            case "716" -> "United States\nRegion: Buffalo, NY";
            case "717" -> "United States\nRegion: Lancaster, PA";
            case "718" -> "United States\nRegion: New York, NY";
            case "719" -> "United States\nRegion: Colorado Springs, CO";
            case "720" -> "United States\nRegion: Denver, CO";
            case "724" -> "United States\nRegion: New Castle, PA";
            case "725" -> "United States\nRegion: Las Vegas, NV";
            case "726" -> "United States\nRegion: San Antonio, TX";
            case "727" -> "United States\nRegion: St. Petersburg, FL";
            case "731" -> "United States\nRegion: Jackson, TN";
            case "732" -> "United States\nRegion: Toms River, NJ";
            case "734" -> "United States\nRegion: Ann Arbor, MI";
            case "737" -> "United States\nRegion: Austin, TX";
            case "740" -> "United States\nRegion: Newark, OH";
            case "743" -> "United States\nRegion: Greensboro, NC";
            case "747" -> "United States\nRegion: Los Angeles, CA";
            case "754" -> "United States\nRegion: Fort Lauderdale, FL";
            case "757" -> "United States\nRegion: Virginia Beach, VA";
            case "760" -> "United States\nRegion: Oceanside, CA";
            case "762" -> "United States\nRegion: Augusta, GA";
            case "763" -> "United States\nRegion: Brooklyn Park, MN";
            case "765" -> "United States\nRegion: Muncie, IN";
            case "769" -> "United States\nRegion: Jackson, MS";
            case "770" -> "United States\nRegion: Roswell, GA";
            case "771" -> "United States\nRegion: District of Columbia";
            case "772" -> "United States\nRegion: Port St. Lucie, FL";
            case "773" -> "United States\nRegion: Chicago, IL";
            case "774" -> "United States\nRegion: Worcester, MA";
            case "775" -> "United States\nRegion: Reno, NV";
            case "779" -> "United States\nRegion: Rockford, IL";
            case "781" -> "United States\nRegion: Boston, MA";
            case "785" -> "United States\nRegion: Topeka, KS";
            case "786" -> "United States\nRegion: Miami, FL";
            case "787" -> "United States\nRegion: Puerto Rico";
            case "801" -> "United States\nRegion: Salt Lake City, UT";
            case "802" -> "United States\nRegion: Vermont";
            case "803" -> "United States\nRegion: Columbia, SC";
            case "804" -> "United States\nRegion: Richmond, VA";
            case "805" -> "United States\nRegion: Oxnard, CA";
            case "806" -> "United States\nRegion: Lubbock, TX";
            case "808" -> "United States\nRegion: Hawaii";
            case "810" -> "United States\nRegion: Flint, MI";
            case "812" -> "United States\nRegion: Evansville, IN";
            case "813" -> "United States\nRegion: Tampa, FL";
            case "814" -> "United States\nRegion: Erie, PA";
            case "815" -> "United States\nRegion: Rockford, IL";
            case "816" -> "United States\nRegion: Kansas City, MO";
            case "817" -> "United States\nRegion: Fort Worth, TX";
            case "818" -> "United States\nRegion: Los Angeles, CA";
            case "820" -> "United States\nRegion: Oxnard, CA";
            case "826" -> "United States\nRegion: Roanoke, VA";
            case "828" -> "United States\nRegion: Asheville, NC";
            case "830" -> "United States\nRegion: New Braunfels, TX";
            case "831" -> "United States\nRegion: Salinas, CA";
            case "832" -> "United States\nRegion: Houston, TX";
            case "835" -> "United States\nRegion: Allentown, PA";
            case "838" -> "United States\nRegion: Albany, NY";
            case "839" -> "United States\nRegion: Columbia, SC";
            case "840" -> "United States\nRegion: San Bernardino, CA";
            case "843" -> "United States\nRegion: Charleston, SC";
            case "845" -> "United States\nRegion: New City, NY";
            case "847" -> "United States\nRegion: Elgin, IL";
            case "848" -> "United States\nRegion: Toms River, NJ";
            case "850" -> "United States\nRegion: Tallahassee, FL";
            case "854" -> "United States\nRegion: Charleston, SC";
            case "856" -> "United States\nRegion: Camden, NJ";
            case "857" -> "United States\nRegion: Boston, MA";
            case "858" -> "United States\nRegion: San Diego, CA";
            case "859" -> "United States\nRegion: Lexington-Fayette, KY";
            case "860" -> "United States\nRegion: Hartford, CT";
            case "862" -> "United States\nRegion: Newark, NJ";
            case "863" -> "United States\nRegion: Lakeland, FL";
            case "864" -> "United States\nRegion: Greenville, SC";
            case "865" -> "United States\nRegion: Knoxville, TN";
            case "870" -> "United States\nRegion: Jonesboro, AR";
            case "872" -> "United States\nRegion: Chicago, IL";
            case "878" -> "United States\nRegion: Pittsburgh, PA";
            case "901" -> "United States\nRegion: Memphis, TN";
            case "903" -> "United States\nRegion: Tyler, TX";
            case "904" -> "United States\nRegion: Jacksonville, FL";
            case "906" -> "United States\nRegion: Marquette, MI";
            case "907" -> "United States\nRegion: Alaska";
            case "908" -> "United States\nRegion: Elizabeth, NJ";
            case "909" -> "United States\nRegion: San Bernardino, CA";
            case "910" -> "United States\nRegion: Fayetteville, NC";
            case "912" -> "United States\nRegion: Savannah, GA";
            case "913" -> "United States\nRegion: Overland Park, KS";
            case "914" -> "United States\nRegion: Yonkers, NY";
            case "915" -> "United States\nRegion: El Paso, TX";
            case "916" -> "United States\nRegion: Sacramento, CA";
            case "917" -> "United States\nRegion: New York, NY";
            case "918" -> "United States\nRegion: Tulsa, OK";
            case "919" -> "United States\nRegion: Raleigh, NC";
            case "920" -> "United States\nRegion: Green Bay, WI";
            case "925" -> "United States\nRegion: Concord, CA";
            case "928" -> "United States\nRegion: Yuma, AZ";
            case "929" -> "United States\nRegion: New York, NY";
            case "930" -> "United States\nRegion: Evansville, IN";
            case "931" -> "United States\nRegion: Clarksville, TN";
            case "934" -> "United States\nRegion: Brentwood, NY";
            case "936" -> "United States\nRegion: Conroe, TX";
            case "937" -> "United States\nRegion: Dayton, OH";
            case "938" -> "United States\nRegion: Huntsville, AL";
            case "939" -> "United States\nRegion: Puerto Rico";
            case "940" -> "United States\nRegion: Denton, TX";
            case "941" -> "United States\nRegion: North Port, FL";
            case "943" -> "United States\nRegion: Atlanta, GA";
            case "945" -> "United States\nRegion: Dallas, TX";
            case "947" -> "United States\nRegion: Troy, MI";
            case "948" -> "United States\nRegion: Virginia Beach, VA";
            case "949" -> "United States\nRegion: Irvine, CA";
            case "951" -> "United States\nRegion: Riverside, CA";
            case "952" -> "United States\nRegion: Bloomington, MN";
            case "954" -> "United States\nRegion: Fort Lauderdale, FL";
            case "956" -> "United States\nRegion: Laredo, TX";
            case "959" -> "United States\nRegion: Hartford, CT";
            case "970" -> "United States\nRegion: Fort Collins, CO";
            case "971" -> "United States\nRegion: Portland, OR";
            case "972" -> "United States\nRegion: Dallas, TX";
            case "973" -> "United States\nRegion: Newark, NJ";
            case "978" -> "United States\nRegion: Lowell, MA";
            case "979" -> "United States\nRegion: College Station, TX";
            case "980" -> "United States\nRegion: Charlotte, NC";
            case "983" -> "United States\nRegion: Denver, CO";
            case "984" -> "United States\nRegion: Raleigh, NC";
            case "985" -> "United States\nRegion: Houma, LA";
            case "986" -> "United States\nRegion: Idaho";
            case "989" -> "United States\nRegion: Saginaw, MI";
            case "204" -> "Canada\nRegion: Manitoba";
            case "226" -> "Canada\nRegion: London, ON";
            case "236" -> "Canada\nRegion: Vancouver, BC";
            case "249" -> "Canada\nRegion: Sudbury, ON";
            case "250" -> "Canada\nRegion: Kelowna, BC";
            case "263" -> "Canada\nRegion: Montreal, QC";
            case "289" -> "Canada\nRegion: Hamilton, ON";
            case "306" -> "Canada\nRegion: Saskatchewan";
            case "343" -> "Canada\nRegion: Ottawa, ON";
            case "354" -> "Canada\nRegion: Granby, QC";
            case "365" -> "Canada\nRegion: Hamilton, ON";
            case "367" -> "Canada\nRegion: Quebec, QC";
            case "368" -> "Canada\nRegion: Calgary, AB";
            case "403" -> "Canada\nRegion: Calgary, AB";
            case "416" -> "Canada\nRegion: Toronto, ON";
            case "418" -> "Canada\nRegion: Quebec, QC";
            case "431" -> "Canada\nRegion: Manitoba";
            case "437" -> "Canada\nRegion: Toronto, ON";
            case "438" -> "Canada\nRegion: Montreal, QC";
            case "450" -> "Canada\nRegion: Granby, QC";
            case "468" -> "Canada\nRegion: Sherbrooke, QC";
            case "474" -> "Canada\nRegion: Saskatchewan";
            case "506" -> "Canada\nRegion: New Brunswick";
            case "514" -> "Canada\nRegion: Montreal, QC";
            case "519" -> "Canada\nRegion: London, ON";
            case "548" -> "Canada\nRegion: London, ON";
            case "579" -> "Canada\nRegion: Granby, QC";
            case "581" -> "Canada\nRegion: Quebec, QC";
            case "584" -> "Canada\nRegion: Manitoba";
            case "587" -> "Canada\nRegion: Calgary, AB";
            case "604" -> "Canada\nRegion: Vancouver, BC";
            case "613" -> "Canada\nRegion: Ottawa, ON";
            case "639" -> "Canada\nRegion: Saskatchewan";
            case "647" -> "Canada\nRegion: Toronto, ON";
            case "672" -> "Canada\nRegion: Vancouver, BC";
            case "683" -> "Canada\nRegion: Sudbury, ON";
            case "705" -> "Canada\nRegion: Sudbury, ON";
            case "709" -> "Canada\nRegion: Newfoundland/Labrador";
            case "742" -> "Canada\nRegion: Hamilton, ON";
            case "753" -> "Canada\nRegion: Ottawa, ON";
            case "778" -> "Canada\nRegion: Vancouver, BC";
            case "780" -> "Canada\nRegion: Edmonton, AB";
            case "782" -> "Canada\nRegion: Nova Scotia/PE Island";
            case "807" -> "Canada\nRegion: Kenora, ON";
            case "819" -> "Canada\nRegion: Sherbrooke, QC";
            case "825" -> "Canada\nRegion: Calgary, AB";
            case "867" -> "Canada\nRegion: Northern Canada";
            case "873" -> "Canada\nRegion: Sherbrooke, QC";
            case "902" -> "Canada\nRegion: Nova Scotia/PE Island";
            case "905" -> "Canada\nRegion: Hamilton, ON";
            case "242" -> "Bahamas";
            case "246" -> "Barbados";
            case "809", "829", "849" -> "Dominican Republic";
            case "876" -> "Jamaica";
            default -> throw new ThereIsNoAreaCodeException(phoneNumber.getAreaCode());
        };
    }

    private static String getBrazilianStateByAreaCode(Integer areaCode){
        if(areaCode >= 11 && areaCode <= 19){
            return "\nState: São Paulo";
        }else if(areaCode == 21 || areaCode == 22 || areaCode == 24){
            return "\nState: Rio de Janeiro";
        }else if(areaCode == 27 || areaCode == 28){
            return "\nState: Espírito Santo";
        }else if((areaCode >= 31 && areaCode <= 35) || areaCode == 37 || areaCode == 38){
            return "\nState: Minas Gerais";
        }else if(areaCode >= 41 && areaCode <= 46){
            return "\nState: Paraná";
        }else if(areaCode >= 47 && areaCode <= 49){
            return "\nState: Santa Catarina";
        }else if(areaCode == 51 || (areaCode >= 53 && areaCode <= 55)){
            return "\nState: Rio Grande do Sul";
        }else if(areaCode == 61){
            return "\nState: Distrito Federal";
        }else if(areaCode == 62 || areaCode == 64){
            return "\nState: Goiás";
        }else if(areaCode == 63){
            return "\nState: Tocantins";
        }else if(areaCode == 65 || areaCode == 66){
            return "\nState: Mato Grosso";
        }else if(areaCode == 67){
            return "\nState: Mato Grosso do Sul";
        }else if(areaCode == 68){
            return "\nState: Acre";
        }else if(areaCode == 69){
            return "\nState: Rondônia";
        }else if(areaCode == 71 || (areaCode >= 73 && areaCode <= 75) || areaCode == 77){
            return "\nState: Bahia";
        }else if(areaCode == 79){
            return "\nState: Sergipe";
        }else if(areaCode == 81 || areaCode == 87){
            return "\nState: Pernambuco";
        }else if(areaCode == 82){
            return "\nState: Alagoas";
        }else if(areaCode == 83){
            return "\nState: Paraíba";
        }else if(areaCode == 84){
            return "\nState: Rio Grande do Norte";
        }else if(areaCode == 85 || areaCode == 88){
            return "\nState: Ceará";
        }else if(areaCode == 86 || areaCode == 89){
            return "\nState: Piauí";
        }else if(areaCode == 91 || areaCode == 93 || areaCode == 94){
            return "\nState: Pará";
        }else if(areaCode == 92 || areaCode == 97){
            return "\nState: Amazonas";
        }else if(areaCode == 95){
            return "\nState: Roraima";
        }else if(areaCode == 96){
            return "\nState: Amapá";
        }else if(areaCode == 98 || areaCode == 99){
            return "\nState: Maranhão";
        }else{
            throw new ThereIsNoAreaCodeException(areaCode, "Brazil");
        }
    }

    public static String getCountryByDDI(PhoneNumber phoneNumber){
        return switch (phoneNumber.getDDI()) {
            case "1" -> getUsOrCanadaRegionByAreaCode(phoneNumber);
            case "20" -> "Egypt";
            case "211" -> "South Sudan";
            case "212" -> "Morocco";
            case "213" -> "Algeria";
            case "216" -> "Tunisia";
            case "218" -> "Libya";
            case "220" -> "The Gambia";
            case "221" -> "Senegal";
            case "222" -> "Mauritania";
            case "223" -> "Mali";
            case "224" -> "Guinea";
            case "225" -> "Côte d'Ivoire (Ivory Coast)";
            case "226" -> "Burkina Faso";
            case "227" -> "Niger";
            case "228" -> "Togo";
            case "229" -> "Benin";
            case "230" -> "Mauritius";
            case "231" -> "Liberia";
            case "232" -> "Sierra Leone";
            case "233" -> "Ghana";
            case "234" -> "Nigeria";
            case "235" -> "Chad";
            case "236" -> "Central African Republic";
            case "237" -> "Cameroon";
            case "238" -> "Cape Verde";
            case "239" -> "São Tomé and Príncipe";
            case "240" -> "Equatorial Guinea";
            case "241" -> "Gabon";
            case "242" -> "Republic of the Congo (Brazzaville)";
            case "243" -> "Democratic Republic of the Congo (Kinshasa)";
            case "244" -> "Angola";
            case "245" -> "Guinea-Bissau";
            case "246" -> "British Indian Ocean Territory";
            case "247" -> "Ascension Island";
            case "248" -> "Seychelles";
            case "249" -> "Sudan";
            case "250" -> "Rwanda";
            case "251" -> "Ethiopia";
            case "252" -> "Somalia (also used in Somaliland)";
            case "253" -> "Djibouti";
            case "254" -> "Kenya";
            case "255" -> "Tanzania";
            case "256" -> "Uganda";
            case "257" -> "Burundi";
            case "258" -> "Mozambique";
            case "259" -> "Zanzibar";
            case "260" -> "Zambia";
            case "261" -> "Madagascar";
            case "262" -> "Réunion and Mayotte";
            case "263" -> "Zimbabwe";
            case "264" -> "Namibia";
            case "265" -> "Malawi";
            case "266" -> "Lesotho";
            case "267" -> "Botswana";
            case "268" -> "Swaziland";
            case "269" -> "Comoros";
            case "27" -> "South Africa";
            case "290" -> "Saint Helena";
            case "291" -> "Eritrea";
            case "297" -> "Aruba";
            case "298" -> "Faroe Islands";
            case "299" -> "Greenland";
            case "30" -> "Greece";
            case "31" -> "The Netherlands";
            case "32" -> "Belgium";
            case "33" -> "France";
            case "34" -> "Spain";
            case "350" -> "Gibraltar";
            case "351" -> "Portugal";
            case "352" -> "Luxembourg";
            case "353" -> "Ireland";
            case "354" -> "Iceland";
            case "355" -> "Albania";
            case "356" -> "Malta";
            case "357" -> "Cyprus";
            case "358" -> "Finland";
            case "359" -> "Bulgaria";
            case "36" -> "Hungary";
            case "370" -> "Lithuania";
            case "371" -> "Latvia";
            case "372" -> "Estonia";
            case "373" -> "Moldova";
            case "374" -> "Armenia";
            case "375" -> "Belarus";
            case "376" -> "Andorra";
            case "377" -> "Monaco";
            case "378" -> "San Marino";
            case "379" -> "Vatican City";
            case "380" -> "Ukraine";
            case "381" -> "Serbia";
            case "382" -> "Montenegro";
            case "385" -> "Croatia";
            case "386" -> "Slovenia";
            case "387" -> "Bosnia and Herzegovina";
            case "389" -> "North Macedonia";
            case "39" -> "Italy";
            case "40" -> "Romania";
            case "41" -> "Switzerland";
            case "420" -> "Czech Republic";
            case "421" -> "Slovakia";
            case "423" -> "Liechtenstein";
            case "43" -> "Austria";
            case "44" -> "United Kingdom";
            case "45" -> "Denmark";
            case "46" -> "Sweden";
            case "47" -> "Norway";
            case "48" -> "Poland";
            case "49" -> "Germany";
            case "500" -> "Falkland Islands";
            case "501" -> "Belize";
            case "502" -> "Guatemala";
            case "503" -> "El Salvador";
            case "504" -> "Honduras";
            case "505" -> "Nicaragua";
            case "506" -> "Costa Rica";
            case "507" -> "Panama";
            case "508" -> "Saint-Pierre and Miquelon";
            case "509" -> "Haiti";
            case "51" -> "Peru";
            case "52" -> "Mexico";
            case "53" -> "Cuba";
            case "54" -> "Argentina";
            case "55" -> "Brazil" + getBrazilianStateByAreaCode(Integer.parseInt(phoneNumber.getAreaCode()));
            case "56" -> "Chile";
            case "57" -> "Colombia";
            case "58" -> "Venezuela";
            case "590" -> "Guadeloupe";
            case "591" -> "Bolivia";
            case "592" -> "Guyana";
            case "593" -> "Ecuador";
            case "594" -> "French Guiana";
            case "595" -> "Paraguay";
            case "596" -> "Martinique";
            case "597" -> "Suriname";
            case "598" -> "Uruguay";
            case "599" -> "Curaçao and the Caribbean Netherlands";
            case "60" -> "Malaysia";
            case "61" -> "Australia";
            case "62" -> "Indonesia";
            case "63" -> "Philippines";
            case "64" -> "New Zealand";
            case "65" -> "Singapore";
            case "66" -> "Thailand";
            case "670" -> "Timor-Leste";
            case "673" -> "Brunei";
            case "674" -> "Nauru";
            case "675" -> "Papua New Guinea";
            case "676" -> "Tonga";
            case "677" -> "Solomon Islands";
            case "678" -> "Vanuatu";
            case "679" -> "Fiji";
            case "680" -> "Palau";
            case "681" -> "Wallis and Futuna";
            case "682" -> "Cook Islands";
            case "683" -> "Niue Island";
            case "685" -> "Samoa";
            case "686" -> "Kiribati, Gilbert Islands";
            case "687" -> "New Caledonia";
            case "688" -> "Tuvalu";
            case "689" -> "French Polynesia";
            case "690" -> "Tokelau";
            case "691" -> "Federated States of Micronesia";
            case "692" -> "Marshall Islands";
            case "7" -> "Russia or Kazakhstan";
            case "81" -> "Japan";
            case "82" -> "South Korea";
            case "84" -> "Vietnam";
            case "850" -> "North Korea";
            case "852" -> "Hong Kong";
            case "853" -> "Macau";
            case "855" -> "Cambodia";
            case "856" -> "Laos";
            case "86" -> "China";
            case "880" -> "Bangladesh";
            case "90" -> "Turkey";
            case "91" -> "India";
            case "92" -> "Pakistan";
            case "93" -> "Afghanistan";
            case "94" -> "Sri Lanka";
            case "95" -> "Myanmar";
            case "960" -> "Maldives";
            case "961" -> "Lebanon";
            case "962" -> "Jordan";
            case "963" -> "Syria";
            case "964" -> "Iraq";
            case "965" -> "Kuwait";
            case "966" -> "Saudi Arabia";
            case "967" -> "Yemen";
            case "968" -> "Oman";
            case "971" -> "United Arab Emirates";
            case "972" -> "Israel";
            case "973" -> "Bahrain";
            case "974" -> "Qatar";
            case "975" -> "Bhutan";
            case "976" -> "Mongolia";
            case "977" -> "Nepal";
            case "98" -> "Iran";
            case "992" -> "Tajikistan";
            case "993" -> "Turkmenistan";
            case "994" -> "Azerbaijan";
            case "995" -> "Georgia";
            case "996" -> "Kyrgyzstan";
            case "998" -> "Uzbekistan";
            default -> throw new ThereIsNoDDIException(phoneNumber.getDDI());
        };
    }
}
